/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations, Html } from "@react-three/drei";
import styles from "./citymodel.module.scss";

export function CityModel(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "/models/ActualWebsiteModel1-v2.glb"
  );
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="Circle002"
          geometry={nodes.Circle002.geometry}
          material={materials["Material__188.001"]}
          position={[1.485, 28.162, 5.106]}
          rotation={[Math.PI / 2, -0.262, 0]}
          scale={[0.605, 0.55, 0.55]}
        />
        <mesh
          name="Plane261"
          geometry={nodes.Plane261.geometry}
          material={materials["Material__188.001"]}
          position={[6.648, 6.776, 0.019]}
          rotation={[Math.PI, 1.571, 0]}
          scale={1.1}
        />
        <mesh
          name="Gear1006"
          geometry={nodes.Gear1006.geometry}
          material={materials["Material__188.001"]}
          position={[42.216, 7.738, -9.619]}
          rotation={[Math.PI / 2, 0.262, 0]}
          scale={1.1}
        />
        <mesh
          name="Empy"
          geometry={nodes.Empy.geometry}
          material={materials["Material__188.001"]}
          position={[33.525, 7, -9.173]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={1.1}
        />
        <group
          name="Empty121"
          position={[47.077, 12.805, -9.71]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={1.1}
        >
          <mesh
            name="BrassPipe1406"
            geometry={nodes.BrassPipe1406.geometry}
            material={materials["Material__188.001"]}
            position={[0, -9.639, 0.564]}
            rotation={[0, -1.571, 0]}
            scale={[2.1, 3.036, 2.1]}
          />
        </group>
        <group name="Empty113" position={[39.063, 4.174, -3.243]} scale={1.1} />
        <group
          name="Empty047"
          position={[57.157, 4.175, -3.243]}
          rotation={[-Math.PI, 0, 0]}
          scale={-1.1}
        />
        <mesh
          name="BrassPipe1311"
          geometry={nodes.BrassPipe1311.geometry}
          material={materials["Material__188.001"]}
          position={[33.9, 3.87, -3.423]}
          rotation={[Math.PI / 2, 0, Math.PI]}
          scale={[1.191, 0.636, 1.191]}
        />
        <mesh
          name="BrassPipe1313"
          geometry={nodes.BrassPipe1313.geometry}
          material={materials["Material__188.001"]}
          position={[33.9, 3.87, -3.992]}
          rotation={[Math.PI / 2, 0, Math.PI]}
          scale={[2.251, 0.469, 2.251]}
        />
        <mesh
          name="Gear1026"
          geometry={nodes.Gear1026.geometry}
          material={materials["Material__188.001"]}
          position={[33.9, 3.87, -3.319]}
          rotation={[-Math.PI / 2, -1.017, 0]}
          scale={[1.83, 1.9, 1.83]}
        />
        <mesh
          name="Brass90Turn1249"
          geometry={nodes.Brass90Turn1249.geometry}
          material={materials["Material__188.001"]}
          position={[38.907, 4.251, -2.592]}
          rotation={[-Math.PI / 2, 0, 1.125]}
          scale={[-1.99, -2.189, -1.99]}
        />
        <mesh
          name="WoodPlankWall13752"
          geometry={nodes.WoodPlankWall13752.geometry}
          material={materials["Material__188.001"]}
          position={[-52.183, 18.762, 12.523]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={[-0.803, -0.863, -0.803]}
        />
        <mesh
          name="WoodPlankWall13754"
          geometry={nodes.WoodPlankWall13754.geometry}
          material={materials["Material__188.001"]}
          position={[-53.554, 15.516, 9.779]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[-0.803, -0.863, -0.803]}
        />
        <mesh
          name="Empy003"
          geometry={nodes.Empy003.geometry}
          material={materials["Material__188.001"]}
          position={[-49.698, 6.633, 15.489]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <group
          name="Empty154"
          position={[-50.187, 12.805, 3.17]}
          rotation={[0, -Math.PI / 2, 0]}
        >
          <mesh
            name="BrassPipe1694"
            geometry={nodes.BrassPipe1694.geometry}
            material={materials["Material__188.001"]}
            position={[0, -9.525, 0]}
            rotation={[0, -1.571, 0]}
            scale={[2.1, 3.036, 2.1]}
          />
          {/* <Html className={styles.marker} position={[0, 0, 0]} rotation={[0, 0, 0]}>
            <h1>About</h1>
            <div className={styles.line}></div>
          </Html> */}
        </group>
        <group
          name="Empty185"
          position={[-44.307, 4.064, 11.828]}
          rotation={[0, 1.571, 0]}
        />
        <group
          name="Empty190"
          position={[-44.307, 7.308, 10.455]}
          rotation={[0, 1.571, 0]}
        />
        <mesh
          name="BrassPipe1752"
          geometry={nodes.BrassPipe1752.geometry}
          material={materials["Material__188.001"]}
          position={[-43.151, 8.879, 9.191]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[-2.316, -1.422, -2.316]}
        />
        <mesh
          name="Brass90Turn1497"
          geometry={nodes.Brass90Turn1497.geometry}
          material={materials["Material__188.001"]}
          position={[-43.151, 5.654, 9.191]}
          rotation={[-1.571, 0, Math.PI]}
          scale={[-1.809, -1.99, -1.809]}
        />
        <mesh
          name="Brass90Turn1498"
          geometry={nodes.Brass90Turn1498.geometry}
          material={materials["Material__188.001"]}
          position={[-43.151, 4.984, 9.927]}
          rotation={[-Math.PI, 0, 0]}
          scale={[-1.809, -1.99, -1.809]}
        />
        <mesh
          name="BrassPipe1754"
          geometry={nodes.BrassPipe1754.geometry}
          material={materials["Material__188.001"]}
          position={[-45.355, 4.237, 17.379]}
          rotation={[Math.PI / 2, 0, Math.PI]}
          scale={[0.532, 1.174, 0.532]}
        />
        <mesh
          name="Brass90Turn1855"
          geometry={nodes.Brass90Turn1855.geometry}
          material={materials["Material__188.001"]}
          position={[45.516, 1.729, -35.905]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={[2.316, 2.548, 2.316]}
        />
        <mesh
          name="BrassPipe11469"
          geometry={nodes.BrassPipe11469.geometry}
          material={materials["Material__188.001"]}
          position={[54.823, 10.254, -30.306]}
          rotation={[Math.PI / 2, 0, 1.571]}
          scale={[2.316, 1.045, 2.316]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/ActualWebsiteModel1-v2.glb");
