/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, {useRef, useMemo, useContext, createContext} from 'react'
import {useGLTF, Merged, useAnimations} from '@react-three/drei'

const context = createContext()

export function TestInstances({children, ...props}) {
    const {nodes} = useGLTF('/models/quarter.glb')
    const instances = useMemo(
        () => ({
            Plane: nodes.Plane004,
            Plane1: nodes.Plane004_1,
            Plane2: nodes.Plane167,
            Empty: nodes.Empty121,
            Gear: nodes.Gear1016,
            Plane3: nodes.Plane237,
            TallWindowInset: nodes.TallWindowInset,
            Plane4: nodes.Plane056,
            BrassPipe: nodes.BrassPipe1001,
        }),
        [nodes]
    )
    return (
        <Merged meshes={instances} {...props}>
            {(instances) => <context.Provider value={instances} children={children}/>}
        </Merged>
    )
}

export function TestComp(props) {
    const instances = useContext(context)
    const group = useRef()
    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Scene">
                <group name="Floor" scale={80}>
                    <instances.Plane name="Plane004"/>
                    <instances.Plane1 name="Plane004_1"/>
                </group>
                <instances.Plane2
                    name="Plane167"
                    position={[-24.6, 1.7, 12.9]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={[2.4, 2.4, 1]}
                />
                <instances.Empty name="Empty121" position={[-24.6, 12.8, 13.7]}/>
                <group name="Empy" position={[-12.3, 6.7, 13.2]}>
                    <instances.Gear
                        name="Gear1016"
                        rotation={[2.6, 0, -Math.PI / 2]}
                        scale={[1.7, 1.8, 1.7]}
                    />
                </group>
                <instances.Plane3
                    name="Plane237"
                    position={[30.9, 0.1, 0.9]}
                    rotation={[0, Math.PI / 2, 0]}
                    scale={3}
                />
                <instances.Plane3
                    name="Plane240"
                    position={[24.9, 0.1, 0.9]}
                    rotation={[0, Math.PI / 2, 0]}
                    scale={3}
                />
                <instances.TallWindowInset
                    name="TallWindowInset"
                    position={[18.7, -3.7, -8.5]}
                    rotation={[0, Math.PI / 2, 0]}
                />
                <instances.Plane4
                    name="Plane056"
                    position={[-9.3, -12.5, -6.3]}
                    rotation={[Math.PI / 2, 0, 0]}
                />
                <instances.BrassPipe
                    name="BrassPipe1001"
                    position={[34.8, 5.9, -7.5]}
                    rotation={[0, 0, Math.PI]}
                    scale={1.2}
                />
                <instances.BrassPipe
                    name="BrassPipe1002"
                    position={[34.8, 5.9, -8.4]}
                    rotation={[0, 0, Math.PI]}
                    scale={1.2}
                />
                <instances.BrassPipe
                    name="BrassPipe1003"
                    position={[34.8, 3.2, -7.5]}
                    rotation={[0, 0, Math.PI]}
                    scale={1.2}
                />
            </group>
        </group>
    )
}

useGLTF.preload('/models/quarter.glb')
