/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Events({ scale = 1, position = [0, 0, 0], ...props }) {
  const { nodes, materials } = useGLTF("/models/BoardWebsiteEvents.glb");
  return (
    <group {...props} dispose={null} position={position} scale={scale}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={materials["Material.001"]}
        position={[-0.23, -0.943, -0.657]}
        scale={[1.032, 1, 1]}
      />
      <group position={[-0.253, -0.942, -0.628]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Text163.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Text163_1.geometry}
          material={materials.Material}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/BoardWebsiteEvents.glb");
