/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Contactus({ scale = 1, position = [0, 0, 0], ...props }) {
  const { nodes, materials } = useGLTF("/models/ContactUsModel.glb");
  return (
    <group {...props} dispose={null} position={position} scale={scale}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text001.geometry}
        material={materials["Material__188.001"]}
        position={[128.22, -0.004, 6.064]}
        scale={10}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane2076.geometry}
        material={materials["Material__188.001"]}
        position={[128.22, -0.004, 6.064]}
        scale={[10.315, 10, 10]}
      />
    </group>
  );
}

useGLTF.preload("/models/ContactUsModel.glb");
