/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function TestComp2(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "/models/ActualWebsiteModel-v1Corrected.glb"
  );
  const { actions, names } = useAnimations(animations, group);

  useEffect(() => {
    for (const name of names) {
      actions[name].play();
    }
  }, []);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="Circle002"
          geometry={nodes.Circle002.geometry}
          material={materials["Material__188.001"]}
          position={[3.265, 24.726, 4.639]}
          rotation={[Math.PI / 2, -0.262, 0]}
          scale={0.5}
        />
        <mesh
          name="Plane261"
          geometry={nodes.Plane261.geometry}
          material={materials["Material__188.001"]}
          position={[8.031, 7.672, 0.014]}
          rotation={[Math.PI, Math.PI / 2, 0]}
        />
        <mesh
          name="Gear1006"
          geometry={nodes.Gear1006.geometry}
          material={materials["Material__188.001"]}
          position={[42.007, 7.304, -9.353]}
          rotation={[Math.PI / 2, 0.262, 0]}
        />
        <mesh
          name="Empy"
          geometry={nodes.Empy.geometry}
          material={materials["Material__188.001"]}
          position={[34.106, 6.633, -9.511]}
          rotation={[Math.PI, 0, Math.PI]}
        />
        <group
          name="Empty121"
          position={[46.426, 12.805, -10]}
          rotation={[Math.PI, 0, Math.PI]}
        >
          <mesh
            name="BrassPipe1406"
            geometry={nodes.BrassPipe1406.geometry}
            material={materials["Material__188.001"]}
            position={[0, -9.639, 0]}
            rotation={[0, -1.571, 0]}
            scale={[2.1, 3.036, 2.1]}
          />
        </group>
        <group name="Empty113" position={[39.141, 4.064, -4.12]} />
        <group
          name="Empty047"
          position={[55.59, 4.065, -4.12]}
          rotation={[-Math.PI, 0, 0]}
          scale={-1}
        />
        <mesh
          name="BrassPipe1311"
          geometry={nodes.BrassPipe1311.geometry}
          material={materials["Material__188.001"]}
          position={[34.447, 3.788, -3.72]}
          rotation={[Math.PI / 2, 0, Math.PI]}
          scale={[1.083, 0.578, 1.083]}
        />
        <mesh
          name="BrassPipe1313"
          geometry={nodes.BrassPipe1313.geometry}
          material={materials["Material__188.001"]}
          position={[34.447, 3.788, -4.237]}
          rotation={[Math.PI / 2, 0, Math.PI]}
          scale={[2.046, 0.427, 2.046]}
        />
        <mesh
          name="Gear1026"
          geometry={nodes.Gear1026.geometry}
          material={materials["Material__188.001"]}
          position={[34.447, 3.788, -3.625]}
          rotation={[-Math.PI / 2, -1.017, 0]}
          scale={[1.664, 1.727, 1.664]}
        />
        <mesh
          name="Brass90Turn1249"
          geometry={nodes.Brass90Turn1249.geometry}
          material={materials["Material__188.001"]}
          position={[38.999, 4.134, -2.964]}
          rotation={[-Math.PI / 2, 0, 1.125]}
          scale={[-1.809, -1.99, -1.809]}
        />
        <mesh
          name="WoodPlankWall13182"
          geometry={nodes.WoodPlankWall13182.geometry}
          material={materials["Material__188.001"]}
          position={[-0.643, 0.819, -34.634]}
          rotation={[-1.571, 0, 0]}
          scale={[0.803, 0.863, 0.803]}
        />
        <group
          name="Empty158"
          position={[-0.643, 4.065, -35.355]}
          rotation={[Math.PI, -1.571, 0]}
          scale={-1}
        />
        <mesh
          name="WoodPlankWall12383"
          geometry={nodes.WoodPlankWall12383.geometry}
          material={materials["Material__188.001"]}
          position={[-51.434, 10.021, 18.317]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={0.803}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/ActualWebsiteModel-v1Corrected.glb");
