/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, {useRef} from 'react'
import {useGLTF} from '@react-three/drei'

export function TestComp2(props) {
    const {nodes, materials} = useGLTF('/models/TestBuildingJoint.glb')
    return (
        <group {...props} dispose={null}>
            <group scale={80}>
                <mesh geometry={nodes.Plane004.geometry} material={materials['Material.001']}/>
                <mesh geometry={nodes.Plane004_1.geometry} material={materials['Material.002']}/>
            </group>
            <mesh
                geometry={nodes.Roof1033.geometry}
                material={materials.Material__188}
                position={[-34.3, 25.2, 13]}
            />
        </group>
    )
}

useGLTF.preload('/models/TestBuildingJoint.glb')
