/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function TestComp2(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "/models/ActualWebsiteModel-v2.glb"
  );
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="Circle002"
          geometry={nodes.Circle002.geometry}
          material={materials["Material__188.001"]}
          position={[5.693, 26.569, 38.561]}
          rotation={[Math.PI / 2, 0.262, Math.PI]}
          scale={[0.55, 0.5, 0.5]}
        />
        <mesh
          name="Plane261"
          geometry={nodes.Plane261.geometry}
          material={materials["Material__188.001"]}
          position={[1, 7.672, 43.186]}
          rotation={[Math.PI, -1.571, 0]}
        />
        <mesh
          name="Gear1006"
          geometry={nodes.Gear1006.geometry}
          material={materials["Material__188.001"]}
          position={[42.007, 7.304, -9.353]}
          rotation={[Math.PI / 2, 0.262, 0]}
        />
        <mesh
          name="Empy"
          geometry={nodes.Empy.geometry}
          material={materials["Material__188.001"]}
          position={[34.106, 6.633, -9.511]}
          rotation={[Math.PI, 0, Math.PI]}
        />
        <group
          name="Empty121"
          position={[46.426, 12.805, -10]}
          rotation={[Math.PI, 0, Math.PI]}
        >
          <mesh
            name="BrassPipe1406"
            geometry={nodes.BrassPipe1406.geometry}
            material={materials["Material__188.001"]}
            position={[0, -9.639, 0]}
            rotation={[0, -1.571, 0]}
            scale={[2.1, 3.036, 2.1]}
          />
        </group>
        <group name="Empty113" position={[39.141, 4.064, -4.12]} />
        <group
          name="Empty047"
          position={[55.59, 4.065, -4.12]}
          rotation={[-Math.PI, 0, 0]}
          scale={-1}
        />
        <mesh
          name="BrassPipe1311"
          geometry={nodes.BrassPipe1311.geometry}
          material={materials["Material__188.001"]}
          position={[34.447, 3.788, -3.72]}
          rotation={[Math.PI / 2, 0, Math.PI]}
          scale={[1.083, 0.578, 1.083]}
        />
        <mesh
          name="BrassPipe1313"
          geometry={nodes.BrassPipe1313.geometry}
          material={materials["Material__188.001"]}
          position={[34.447, 3.788, -4.237]}
          rotation={[Math.PI / 2, 0, Math.PI]}
          scale={[2.046, 0.427, 2.046]}
        />
        <mesh
          name="Gear1026"
          geometry={nodes.Gear1026.geometry}
          material={materials["Material__188.001"]}
          position={[34.447, 3.788, -3.625]}
          rotation={[-Math.PI / 2, -1.017, 0]}
          scale={[1.664, 1.727, 1.664]}
        />
        <mesh
          name="Brass90Turn1249"
          geometry={nodes.Brass90Turn1249.geometry}
          material={materials["Material__188.001"]}
          position={[38.999, 4.134, -2.964]}
          rotation={[-Math.PI / 2, 0, 1.125]}
          scale={[-1.809, -1.99, -1.809]}
        />
        <mesh
          name="WoodPlankWall13182"
          geometry={nodes.WoodPlankWall13182.geometry}
          material={materials["Material__188.001"]}
          position={[-0.643, 0.819, -34.634]}
          rotation={[-1.571, 0, 0]}
          scale={[0.803, 0.863, 0.803]}
        />
        <group
          name="Empty158"
          position={[-0.643, 4.065, -35.355]}
          rotation={[Math.PI, -1.571, 0]}
          scale={-1}
        />
        <mesh
          name="WoodPlankWall13754"
          geometry={nodes.WoodPlankWall13754.geometry}
          material={materials["Material__188.001"]}
          position={[-54.452, 15.403, 9.779]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[-0.803, -0.863, -0.803]}
        />
        <mesh
          name="Empy003"
          geometry={nodes.Empy003.geometry}
          material={materials["Material__188.001"]}
          position={[-50.596, 6.633, 15.489]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <group
          name="Empty154"
          position={[-51.085, 12.805, 3.17]}
          rotation={[0, -Math.PI / 2, 0]}
        >
          <mesh
            name="BrassPipe1694"
            geometry={nodes.BrassPipe1694.geometry}
            material={materials["Material__188.001"]}
            position={[0, -9.639, 0]}
            rotation={[0, -1.571, 0]}
            scale={[2.1, 3.036, 2.1]}
          />
        </group>
        <group
          name="Empty185"
          position={[-45.206, 4.064, 11.828]}
          rotation={[0, 1.571, 0]}
        />
        <group
          name="Empty190"
          position={[-45.206, 7.308, 10.455]}
          rotation={[0, 1.571, 0]}
        />
        <mesh
          name="BrassPipe1752"
          geometry={nodes.BrassPipe1752.geometry}
          material={materials["Material__188.001"]}
          position={[-44.05, 8.766, 9.191]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[-2.316, -1.422, -2.316]}
        />
        <mesh
          name="Brass90Turn1497"
          geometry={nodes.Brass90Turn1497.geometry}
          material={materials["Material__188.001"]}
          position={[-44.05, 5.54, 9.191]}
          rotation={[-1.571, 0, Math.PI]}
          scale={[-1.809, -1.99, -1.809]}
        />
        <mesh
          name="Brass90Turn1498"
          geometry={nodes.Brass90Turn1498.geometry}
          material={materials["Material__188.001"]}
          position={[-44.05, 4.87, 9.927]}
          rotation={[-Math.PI, 0, 0]}
          scale={[-1.809, -1.99, -1.809]}
        />
        <mesh
          name="BrassPipe1754"
          geometry={nodes.BrassPipe1754.geometry}
          material={materials["Material__188.001"]}
          position={[-46.254, 4.123, 17.379]}
          rotation={[Math.PI / 2, 0, Math.PI]}
          scale={[0.532, 1.174, 0.532]}
        />
        <mesh
          name="WoodPlankWall12385"
          geometry={nodes.WoodPlankWall12385.geometry}
          material={materials["Material__188.001"]}
          position={[-131.748, 8.742, 27.421]}
          rotation={[-1.571, 0, 0]}
          scale={0.803}
        />
        <mesh
          name="WoodPlankWall12387"
          geometry={nodes.WoodPlankWall12387.geometry}
          material={materials["Material__188.001"]}
          position={[-136.855, 8.742, 27.421]}
          rotation={[1.571, 0, 0]}
          scale={-0.803}
        />
        <mesh
          name="Desert_Mountain"
          geometry={nodes.Desert_Mountain.geometry}
          material={materials["Desert Mountain"]}
          position={[17.022, -45.285, 96.95]}
          rotation={[Math.PI, -0.544, Math.PI]}
          scale={[131.255, 168.007, 131.255]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/ActualWebsiteModel-v2.glb");
