/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function ContactBoard({ scale = 1, position = [0, 0, 0], ...props }) {
  const { nodes, materials } = useGLTF("/models/ContactUsBoard.glb");
  return (
    <group {...props} dispose={null} position={position} scale={scale}>
      <mesh
        geometry={nodes.Plane010.geometry}
        material={materials["Material.007"]}
        position={[7.766, 0.232, 11.98]}
        scale={0.695}
      />
      <mesh
        geometry={nodes.Cube002.geometry}
        material={materials["Material.006"]}
        position={[7.881, 0.232, 12.477]}
        scale={[10.775, 1, 1.208]}
      />
      <mesh
        geometry={nodes.Plane011.geometry}
        material={materials["Material.001"]}
        position={[7.881, 0.232, 12.012]}
        scale={[0.888, 0.946, 0.946]}
      />
    </group>
  );
}

useGLTF.preload("/models/ContactUsBoard.glb");
