/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export function ContactBoard({ scale = 1, position = [0, 0, 0], ...props }) {
  const { nodes, materials } = useGLTF('/models/NixEmm.glb')
  return (
    <group {...props} dispose={null} position={position} scale={scale}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={materials['Material.001']}
        position={[1.242, -0.015, -0.181]}
        scale={[1.032, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text002.geometry}
        material={materials['Material.001']}
        position={[1.242, -0.036, -0.181]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Lines001.geometry}
        material={materials.Material}
        position={[-0.621, 0.013, 0.091]}
        scale={[1, 0, 1]}
      />
    </group>
  )
}

useGLTF.preload('/models/NixEmm.glb')