// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// */

// import React, { useRef } from 'react';
// import { useGLTF } from '@react-three/drei';

// export function ContactBoard({ scale = 1, position = [0, 0, 0], ...props }) {
//   const { nodes, materials } = useGLTF('/models/NixEmm.glb')
//   return (
//     <group {...props} dispose={null} position={position} scale={scale}>
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Plane.geometry}
//         material={materials['Material.001']}
//         position={[1.242, -0.015, -0.181]}
//         scale={[1.032, 1, 1]}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Text002.geometry}
//         material={materials['Material.001']}
//         position={[1.242, -0.036, -0.181]}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Lines001.geometry}
//         material={materials.Material}
//         position={[-0.621, 0.013, 0.091]}
//         scale={[1, 0, 1]}
//       />
//     </group>
//   )
// }

// useGLTF.preload('/models/NixEmm.glb')

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function ContactBoard({ scale = 1, position = [0, 0, 0], ...props }) {
  const { nodes, materials } = useGLTF("/models/BoardWebsiteNIX.glb");
  return (
    <group {...props} dispose={null} position={position} scale={scale}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane010.geometry}
        material={materials["Material.007"]}
        position={[7.766, 0.232, 11.98]}
        scale={0.695}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002.geometry}
        material={materials["Material.006"]}
        position={[7.881, 0.232, 12.477]}
        scale={[10.775, 1, 1.208]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane011.geometry}
        material={materials["Material.001"]}
        position={[7.881, 0.232, 12.012]}
        scale={[0.888, 0.946, 0.946]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane012.geometry}
        material={materials["Material.006"]}
        position={[7.881, 0.232, 12.012]}
        scale={[0.888, 0.946, 0.946]}
      />
    </group>
  );
}

useGLTF.preload("/models/BoardWebsiteNIX.glb");
