/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/BoardWebsite.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.AboutUsBack.geometry}
        material={materials["Material.001"]}
        position={[-3.33, 0.04, 0.004]}
        scale={[1.032, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.AboutUsFront.geometry}
        material={materials["Material.004"]}
        position={[-3.33, 0.04, 0.004]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.EventsBack.geometry}
        material={materials["Material.001"]}
        position={[-9.17, 0.055, 0.004]}
        scale={[1.032, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.EventsFront.geometry}
        material={materials["Material.004"]}
        position={[-9.17, 0.055, 0.004]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ContactUsBack.geometry}
        material={materials["Material.001"]}
        position={[3.183, 0.055, 0.004]}
        scale={[1.032, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ContactUsFront.geometry}
        material={materials["Material.004"]}
        position={[3.183, 0.055, 0.004]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SpeakerBack.geometry}
        material={materials["Material.001"]}
        position={[9.007, 0.055, 0.004]}
        scale={[1.032, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SpeakerFront.geometry}
        material={materials["Material.004"]}
        position={[9.007, 0.055, 0.004]}
      />
    </group>
  );
}

useGLTF.preload("/BoardWebsite.glb");
