/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function AboutUsBoard({ scale = 1, position = [0, 0, 0], ...props }) {
  const { nodes, materials } = useGLTF("/models/AboutUsBoard.glb");
  return (
    <group {...props} dispose={null} position={position} scale={scale}>
      <mesh
        geometry={nodes.Plane003.geometry}
        material={materials["Material.001"]}
        position={[0.09, -0.03, 0]}
        scale={[1.032, 1, 1]}
      />
      <mesh
        geometry={nodes.Text088.geometry}
        material={materials.Material}
        position={[0.047, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/models/AboutUsBoard.glb");
