/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function SpeakersBoard({ scale = 1, position = [0, 0, 0], ...props }) {
  const { nodes, materials } = useGLTF("/models/SpeakersBoard.glb");
  return (
    <group {...props} dispose={null} position={position} scale={scale}>
      <mesh
        geometry={nodes.Plane003.geometry}
        material={materials["Material.001"]}
        scale={[1.032, 1, 1]}
      />
      <mesh geometry={nodes.Text089.geometry} material={materials.Material} />
    </group>
  );
}

useGLTF.preload("/models/SpeakersBoard.glb");
